### ISSUE TITLE
Case 20 GPU

### ISSUE THREAD

**Issue by chainsawriot** [Kudusch/reprohack23#35]
Following up #34 , do we want to try the GPU example?

It requires a Nvidia GPU, running 20.04, `nvidia-470`, and CUDA 11.2.

These GPUs: 

https://www.nvidia.com/download/driverResults.aspx/183584/en-us/

**Comment by JBGruber** [comment]
I tried to run this, but the docker-compose looks wrong. I set SNAPSHOT_DATE and OSF_PAT , but I don't know what PROJECT_NODE means:
https://github.com/Kudusch/reprohack23/blob/2a7b18f2587e8a2c5de8e48e8dd212bf1fd78c84/cases/20/docker-compose.yml#L7-L10

**Comment by chainsawriot** [comment]
The `PROJECT_NODE` is [this](https://osf.io/jngkx/), previously it was private, but now it is open and therefore `OSF_PAT` is probably not needed.

I usually have a `.env`

```conf
SNAPSHOT_DATE=2023-05-25
PROJECT_NODE=jngkx
OSF_PAT=......
```

**Comment by JBGruber** [comment]
After a lot of trial and error, the image finally built, only to display the message `pipeline.sh: No such file or directory`. I thought I've seen it, but there is a `pipeline.py` and I didn't check the file type. So unless we can dig it up somehow, this is the end of the line, I think.

**Comment by chainsawriot** [comment]
@JBGruber I think we can conclude.
